// Made by Dr Ali
// Static OBIC service catalog — mirrors the interactive prototype list.

export type CatalogSeedItem = {
  slug: string;
  icon: string;
  colorKey: string | null;
  sortOrder: number;
  nameAr: string;
  nameEn: string;
  nameZh: string;
  descAr: string;
  descEn: string;
  descZh: string;
  priceAr: string;
  priceEn: string;
  priceZh: string;
};

/** Seeded into `services` on migration — public browse catalog. */
export const CATALOG_SEED: CatalogSeedItem[] = [
  {
    slug: 'hotels',
    icon: 'hotel',
    colorKey: 'hotels',
    sortOrder: 1,
    nameAr: 'فنادق',
    nameEn: 'Hotels',
    nameZh: '酒店',
    descAr: 'احجز فنادق في الصين لرحلات العمل.',
    descEn: 'Book hotels across China for business trips.',
    descZh: '为中国商务行程预订酒店。',
    priceAr: 'من 45$/ليلة',
    priceEn: 'From $45/night',
    priceZh: '每晚$45起',
  },
  {
    slug: 'flights',
    icon: 'flight',
    colorKey: 'flights',
    sortOrder: 2,
    nameAr: 'رحلات',
    nameEn: 'Flights',
    nameZh: '机票',
    descAr: 'مساعدة حجز تذاكر الصين.',
    descEn: 'Flight booking assistance for China routes.',
    descZh: '中国航线机票预订协助。',
    priceAr: 'مساعدة من 20$',
    priceEn: 'Assist from $20',
    priceZh: '协助费$20起',
  },
  {
    slug: 'visa',
    icon: 'visa',
    colorKey: 'visa',
    sortOrder: 3,
    nameAr: 'تأشيرة',
    nameEn: 'Visa',
    nameZh: '签证',
    descAr: 'دعم تأشيرات العمل والسياحة للصين.',
    descEn: 'China business / tourist visa support.',
    descZh: '中国商务/旅游签证支持。',
    priceAr: 'من 120$',
    priceEn: 'From $120',
    priceZh: '$120起',
  },
  {
    slug: 'bank',
    icon: 'bank',
    colorKey: 'bank',
    sortOrder: 4,
    nameAr: 'حساب بنكي',
    nameEn: 'Bank Account',
    nameZh: '银行账户',
    descAr: 'فتح حساب محلي بإرشاد.',
    descEn: 'Open a local bank account with guidance.',
    descZh: '协助开立本地银行账户。',
    priceAr: 'من 299$',
    priceEn: 'From $299',
    priceZh: '$299起',
  },
  {
    slug: 'vip',
    icon: 'vip',
    colorKey: 'vip',
    sortOrder: 5,
    nameAr: 'خدمة VIP',
    nameEn: 'VIP Service',
    nameZh: 'VIP服务',
    descAr: 'برنامج كامل: استقبال، فنادق، مصانع.',
    descEn: 'Full VIP itinerary, pickup, factory visits.',
    descZh: '全程VIP：接机、酒店、工厂参观。',
    priceAr: 'عرض مخصص',
    priceEn: 'Custom quote',
    priceZh: '定制报价',
  },
  {
    slug: 'legal',
    icon: 'legal',
    colorKey: null,
    sortOrder: 6,
    nameAr: 'خدمات قانونية',
    nameEn: 'Legal Services',
    nameZh: '法律服务',
    descAr: 'عقود وامتثال ودعم قانوني.',
    descEn: 'Contracts, compliance, and legal support.',
    descZh: '合同、合规与法律支持。',
    priceAr: 'من 199$',
    priceEn: 'From $199',
    priceZh: '$199起',
  },
  {
    slug: 'company',
    icon: 'company',
    colorKey: null,
    sortOrder: 7,
    nameAr: 'تسجيل شركة',
    nameEn: 'Company Registration',
    nameZh: '公司注册',
    descAr: 'سجّل شركتك في الصين.',
    descEn: 'Register your company in China.',
    descZh: '在中国注册公司。',
    priceAr: 'من 499$',
    priceEn: 'From $499',
    priceZh: '$499起',
  },
  {
    slug: 'scholarship',
    icon: 'scholarship',
    colorKey: null,
    sortOrder: 8,
    nameAr: 'منح دراسية',
    nameEn: 'Scholarships',
    nameZh: '奖学金',
    descAr: 'دعم طلبات المنح.',
    descEn: 'Scholarship application support.',
    descZh: '奖学金申请支持。',
    priceAr: 'استشارة مجانية',
    priceEn: 'Consult free',
    priceZh: '免费咨询',
  },
  {
    slug: 'transfer',
    icon: 'transfer',
    colorKey: null,
    sortOrder: 9,
    nameAr: 'تحويل أموال',
    nameEn: 'Money Transfer',
    nameZh: '汇款',
    descAr: 'طلب مساعدة للتحويلات (معلومات V1).',
    descEn: 'Request assistance for transfers (info V1).',
    descZh: '汇款协助申请（信息版V1）。',
    priceAr: 'طلب فقط',
    priceEn: 'Request only',
    priceZh: '仅申请',
  },
  {
    slug: 'ads',
    icon: 'ads',
    colorKey: null,
    sortOrder: 10,
    nameAr: 'إعلانات',
    nameEn: 'Advertisements',
    nameZh: '广告',
    descAr: 'دعم العلامة والإعلانات في الصين.',
    descEn: 'Brand & ads support in China.',
    descZh: '中国市场品牌与广告投放支持。',
    priceAr: 'من 150$',
    priceEn: 'From $150',
    priceZh: '$150起',
  },
  {
    slug: 'biz',
    icon: 'biz',
    colorKey: null,
    sortOrder: 11,
    nameAr: 'خدمات أعمال',
    nameEn: 'Business Services',
    nameZh: '商务服务',
    descAr: 'توريد واجتماعات ودعم تشغيلي.',
    descEn: 'Sourcing, meetings, and ops support.',
    descZh: '采购、会议与运营支持。',
    priceAr: 'من 99$',
    priceEn: 'From $99',
    priceZh: '$99起',
  },
  {
    slug: 'hr',
    icon: 'hr',
    colorKey: null,
    sortOrder: 12,
    nameAr: 'موارد بشرية',
    nameEn: 'Human Resources',
    nameZh: '人力资源',
    descAr: 'توظيف وتنسيق الموارد البشرية.',
    descEn: 'Hiring and HR coordination.',
    descZh: '招聘与人力资源协调。',
    priceAr: 'من 180$',
    priceEn: 'From $180',
    priceZh: '$180起',
  },
  {
    slug: 'insurance',
    icon: 'insurance',
    colorKey: null,
    sortOrder: 13,
    nameAr: 'تأمين',
    nameEn: 'Insurance',
    nameZh: '保险',
    descAr: 'خطط حماية وتأمين.',
    descEn: 'Insurance & protection plans.',
    descZh: '保险与保障方案。',
    priceAr: 'من 50$',
    priceEn: 'From $50',
    priceZh: '$50起',
  },
  {
    slug: 'expand',
    icon: 'expand',
    colorKey: null,
    sortOrder: 14,
    nameAr: 'توسع دولي',
    nameEn: 'International Expansion',
    nameZh: '国际拓展',
    descAr: 'استشارات دخول الأسواق.',
    descEn: 'Go-to-market and expansion advisory.',
    descZh: '市场进入与拓展咨询。',
    priceAr: 'مخصص',
    priceEn: 'Custom',
    priceZh: '定制',
  },
  {
    slug: 'tech',
    icon: 'tech',
    colorKey: null,
    sortOrder: 15,
    nameAr: 'دعم تقني',
    nameEn: 'Technical Support',
    nameZh: '技术支持',
    descAr: 'باقات دعم تقني وتشغيلي.',
    descEn: 'Tech & ops support packages.',
    descZh: '技术与运营支持套餐。',
    priceAr: 'من 80$',
    priceEn: 'From $80',
    priceZh: '$80起',
  },
  {
    slug: 'plan',
    icon: 'plan',
    colorKey: null,
    sortOrder: 16,
    nameAr: 'تخطيط أعمال',
    nameEn: 'Business Planning',
    nameZh: '商业规划',
    descAr: 'ورش تخطيط الأعمال.',
    descEn: 'Business planning workshops.',
    descZh: '商业规划工作坊。',
    priceAr: 'من 220$',
    priceEn: 'From $220',
    priceZh: '$220起',
  },
  {
    slug: 'cars',
    icon: 'cars',
    colorKey: null,
    sortOrder: 17,
    nameAr: 'سيارات',
    nameEn: 'Cars',
    nameZh: '汽车服务',
    descAr: 'تأجير ونقل وخدمات سيارات في الصين.',
    descEn: 'Car rental, transfer, and auto services in China.',
    descZh: '中国汽车租赁、接送与用车服务。',
    priceAr: 'من 35$',
    priceEn: 'From $35',
    priceZh: '$35起',
  },
  {
    slug: 'property',
    icon: 'property',
    colorKey: null,
    sortOrder: 18,
    nameAr: 'عقارات',
    nameEn: 'Property',
    nameZh: '房产服务',
    descAr: 'إيجار وشراء ومكاتب في الصين.',
    descEn: 'Rent, buy, and office space in China.',
    descZh: '中国房产租赁、购买与办公选址。',
    priceAr: 'استشارة مجانية',
    priceEn: 'Consult free',
    priceZh: '免费咨询',
  },
  {
    slug: 'delivery',
    icon: 'delivery',
    colorKey: null,
    sortOrder: 19,
    nameAr: 'توصيل',
    nameEn: 'Delivery',
    nameZh: '快递配送',
    descAr: 'شحن وتوصيل داخل الصين وخارجها.',
    descEn: 'Shipping and delivery within China and abroad.',
    descZh: '中国境内及国际快递配送。',
    priceAr: 'عرض حسب الوزن',
    priceEn: 'Quote by weight',
    priceZh: '按重量报价',
  },
  {
    slug: 'consultations',
    icon: 'consultations',
    colorKey: null,
    sortOrder: 20,
    nameAr: 'استشارات',
    nameEn: 'Consultations',
    nameZh: '咨询服务',
    descAr: 'جلسات استشارية للأعمال والسوق الصيني.',
    descEn: 'Business and China market consultation sessions.',
    descZh: '商务与中国市场咨询会话。',
    priceAr: 'من 79$',
    priceEn: 'From $79',
    priceZh: '$79起',
  },
  {
    slug: 'translation',
    icon: 'translation',
    colorKey: null,
    sortOrder: 21,
    nameAr: 'ترجمة',
    nameEn: 'Translation',
    nameZh: '翻译服务',
    descAr: 'ترجمة مستندات ومرافقة ميدانية.',
    descEn: 'Document translation and on-site interpreting.',
    descZh: '文件翻译与现场口译。',
    priceAr: 'من 25$',
    priceEn: 'From $25',
    priceZh: '$25起',
  },
  {
    slug: 'tourism',
    icon: 'tourism',
    colorKey: null,
    sortOrder: 22,
    nameAr: 'سياحة',
    nameEn: 'Tourism',
    nameZh: '旅游服务',
    descAr: 'برامج سياحية وجولات في الصين.',
    descEn: 'Tour packages and guided trips in China.',
    descZh: '中国旅游套餐与导游行程。',
    priceAr: 'عرض مخصص',
    priceEn: 'Custom quote',
    priceZh: '定制报价',
  },
];
