// Made by Dr Ali
// OBIC WeChat-style mega catalog — parent categories + sub-services.

export type MegaCatalogSubSeed = {
  id: string;
  icon: string;
  sortOrder: number;
  nameAr: string;
  nameEn: string;
  nameZh: string;
  descAr: string;
  descEn: string;
  descZh: string;
  priceAr: string;
  priceEn: string;
  priceZh: string;
  countries?: string[];
};

export type MegaCatalogParentSeed = {
  slug: string;
  icon: string;
  colorKey: string;
  sortOrder: number;
  nameAr: string;
  nameEn: string;
  nameZh: string;
  descAr: string;
  descEn: string;
  descZh: string;
  priceAr: string;
  priceEn: string;
  priceZh: string;
  countries: string[];
  subs: MegaCatalogSubSeed[];
};

/** WeChat-style parent catalog — 10 mega-categories with nested subs. */
export const MEGA_CATALOG_SEED: MegaCatalogParentSeed[] = [
  {
    slug: 'property',
    icon: 'property',
    colorKey: 'property',
    sortOrder: 1,
    nameAr: 'عقارات',
    nameEn: 'Property',
    nameZh: '房产',
    descAr: 'إيجار وشراء ومساحات عمل في الصين وخارجها.',
    descEn: 'Rent, buy, and workspace across China and abroad.',
    descZh: '中国及海外房产租赁、购买与办公选址。',
    priceAr: 'استشارة مجانية',
    priceEn: 'Consult free',
    priceZh: '免费咨询',
    countries: [],
    subs: [
      {
        id: 'villas',
        icon: 'villa',
        sortOrder: 0,
        nameAr: 'فيلات',
        nameEn: 'Villas',
        nameZh: '别墅',
        descAr: 'فيلات فاخرة للإقامة أو الاستثمار.',
        descEn: 'Luxury villas for stay or investment.',
        descZh: '豪华别墅租住或投资。',
        priceAr: 'من 800$/شهر',
        priceEn: 'From $800/mo',
        priceZh: '每月$800起',
      },
      {
        id: 'shared-housing',
        icon: 'group',
        sortOrder: 1,
        nameAr: 'سكن مشترك',
        nameEn: 'Shared Housing',
        nameZh: '合租',
        descAr: 'غرف وشقق مشتركة اقتصادية للطلاب والعمال.',
        descEn: 'Affordable shared rooms and flats.',
        descZh: '经济型合租房间与公寓。',
        priceAr: 'من 200$/شهر',
        priceEn: 'From $200/mo',
        priceZh: '每月$200起',
      },
      {
        id: 'hotels',
        icon: 'hotel',
        sortOrder: 2,
        nameAr: 'فنادق',
        nameEn: 'Hotels',
        nameZh: '酒店',
        descAr: 'حجز فنادق قصيرة المدى.',
        descEn: 'Short-stay hotel booking.',
        descZh: '短期酒店预订。',
        priceAr: 'من 320¥/ليلة',
        priceEn: 'From ¥320/night',
        priceZh: '每晚¥320起',
      },
      {
        id: 'mobile-homes',
        icon: 'rv_hookup',
        sortOrder: 3,
        nameAr: 'بيوت متنقلة',
        nameEn: 'Mobile Homes',
        nameZh: '移动房屋',
        descAr: 'وحدات سكن متنقلة ومؤقتة.',
        descEn: 'Mobile and temporary housing units.',
        descZh: '移动及临时住房单元。',
        priceAr: 'عرض حسب الموقع',
        priceEn: 'Quote by location',
        priceZh: '按地点报价',
      },
      {
        id: 'personal-buildings',
        icon: 'apartment',
        sortOrder: 4,
        nameAr: 'مباني شخصية',
        nameEn: 'Personal Buildings',
        nameZh: '个人楼宇',
        descAr: 'مباني سكنية أو تجارية صغيرة.',
        descEn: 'Small residential or commercial buildings.',
        descZh: '小型住宅或商业楼宇。',
        priceAr: 'عرض مخصص',
        priceEn: 'Custom quote',
        priceZh: '定制报价',
      },
      {
        id: 'sale',
        icon: 'sell',
        sortOrder: 5,
        nameAr: 'بيع عقار',
        nameEn: 'Property Sale',
        nameZh: '房产出售',
        descAr: 'شراء وبيع عقارات بإرشاد.',
        descEn: 'Buy and sell property with guidance.',
        descZh: '房产买卖协助。',
        priceAr: 'استشارة مجانية',
        priceEn: 'Consult free',
        priceZh: '免费咨询',
      },
      {
        id: 'houses',
        icon: 'home',
        sortOrder: 6,
        nameAr: 'منازل',
        nameEn: 'Houses',
        nameZh: '住宅',
        descAr: 'منازل عائلية للإيجار أو الشراء.',
        descEn: 'Family houses for rent or purchase.',
        descZh: '家庭住宅租售。',
        priceAr: 'من 500$/شهر',
        priceEn: 'From $500/mo',
        priceZh: '每月$500起',
      },
      {
        id: 'apartments',
        icon: 'domain',
        sortOrder: 7,
        nameAr: 'شقق',
        nameEn: 'Apartments',
        nameZh: '公寓',
        descAr: 'شقق مفروشة وغير مفروشة.',
        descEn: 'Furnished and unfurnished apartments.',
        descZh: '精装与毛坯公寓。',
        priceAr: 'من 350$/شهر',
        priceEn: 'From $350/mo',
        priceZh: '每月$350起',
      },
      {
        id: 'offices',
        icon: 'business',
        sortOrder: 8,
        nameAr: 'مكاتب',
        nameEn: 'Offices',
        nameZh: '办公室',
        descAr: 'مكاتب ومساحات عمل مشتركة.',
        descEn: 'Offices and co-working spaces.',
        descZh: '办公室与共享工位。',
        priceAr: 'من 400$/شهر',
        priceEn: 'From $400/mo',
        priceZh: '每月$400起',
      },
      {
        id: 'warehouses',
        icon: 'warehouse',
        sortOrder: 9,
        nameAr: 'مستودعات',
        nameEn: 'Warehouses',
        nameZh: '仓库',
        descAr: 'تأجير مستودعات وتخزين تجاري.',
        descEn: 'Warehouse rental and commercial storage.',
        descZh: '仓库租赁与商业仓储。',
        priceAr: 'عرض حسب المساحة',
        priceEn: 'Quote by area',
        priceZh: '按面积报价',
      },
      {
        id: 'property-advice',
        icon: 'real_estate_agent',
        sortOrder: 10,
        nameAr: 'استشارات عقارية',
        nameEn: 'Property Consulting',
        nameZh: '房产咨询',
        descAr: 'استشارة لاختيار العقار المناسب.',
        descEn: 'Advice to choose the right property.',
        descZh: '协助选择合适房产。',
        priceAr: 'استشارة مجانية',
        priceEn: 'Consult free',
        priceZh: '免费咨询',
      },
      {
        id: 'mortgage-finance',
        icon: 'account_balance',
        sortOrder: 11,
        nameAr: 'تمويل عقاري',
        nameEn: 'Property Finance',
        nameZh: '房产融资',
        descAr: 'دعم تمويل شراء العقار.',
        descEn: 'Support for property financing.',
        descZh: '房产融资协助。',
        priceAr: 'حسب الطلب',
        priceEn: 'On request',
        priceZh: '按需报价',
      },
    ],
  },
  {
    slug: 'transport',
    icon: 'directions_car',
    colorKey: 'transport',
    sortOrder: 2,
    nameAr: 'نقل ومواصلات',
    nameEn: 'Transport',
    nameZh: '出行交通',
    descAr: 'رحلات جوية وبرية وبحرية داخل الصين وخارجها.',
    descEn: 'Air, land, and sea transport in China and abroad.',
    descZh: '中国及国际空陆海出行服务。',
    priceAr: 'من 70¥',
    priceEn: 'From ¥70',
    priceZh: '¥70起',
    countries: [],
    subs: [
      {
        id: 'flights',
        icon: 'flight',
        sortOrder: 0,
        nameAr: 'طيران',
        nameEn: 'Flights',
        nameZh: '机票',
        descAr: 'حجز وتعديل تذاكر الطيران.',
        descEn: 'Flight booking and changes.',
        descZh: '机票预订与改签。',
        priceAr: 'حسب المسار · من 300¥',
        priceEn: 'By route · from ¥300',
        priceZh: '按航线 · ¥300起',
      },
      {
        id: 'bullet-train',
        icon: 'train',
        sortOrder: 1,
        nameAr: 'قطار فائق السرعة',
        nameEn: 'Bullet Train',
        nameZh: '高铁',
        descAr: 'حجز قطارات فائقة السرعة في الصين.',
        descEn: 'China high-speed rail booking.',
        descZh: '中国高铁票务。',
        priceAr: 'من 100¥',
        priceEn: 'From ¥100',
        priceZh: '¥100起',
      },
      {
        id: 'trains',
        icon: 'directions_railway',
        sortOrder: 2,
        nameAr: 'قطارات',
        nameEn: 'Trains',
        nameZh: '火车',
        descAr: 'قطارات عادية وإقليمية.',
        descEn: 'Regular and regional trains.',
        descZh: '普通及城际火车。',
        priceAr: 'من 70¥',
        priceEn: 'From ¥70',
        priceZh: '¥70起',
      },
      {
        id: 'buses',
        icon: 'directions_bus',
        sortOrder: 3,
        nameAr: 'حافلات',
        nameEn: 'Buses',
        nameZh: '巴士',
        descAr: 'حافلات بين المدن والمطارات.',
        descEn: 'Intercity and airport buses.',
        descZh: '城际及机场巴士。',
        priceAr: 'من 8$',
        priceEn: 'From $8',
        priceZh: '$8起',
      },
      {
        id: 'taxi',
        icon: 'local_taxi',
        sortOrder: 4,
        nameAr: 'تاكسي',
        nameEn: 'Taxi',
        nameZh: '出租车',
        descAr: 'تاكسي ونقل محلي.',
        descEn: 'Taxi and local rides.',
        descZh: '出租车及本地出行。',
        priceAr: 'من 12$',
        priceEn: 'From $12',
        priceZh: '$12起',
      },
      {
        id: 'vip-taxi',
        icon: 'vip',
        sortOrder: 5,
        nameAr: 'تاكسي VIP',
        nameEn: 'VIP Taxi',
        nameZh: 'VIP专车',
        descAr: 'سيارات فاخرة مع سائق خاص.',
        descEn: 'Premium cars with private driver.',
        descZh: '豪华专车与私人司机。',
        priceAr: 'من 60$',
        priceEn: 'From $60',
        priceZh: '$60起',
      },
      {
        id: 'e-bikes',
        icon: 'electric_scooter',
        sortOrder: 6,
        nameAr: 'دراجات كهربائية',
        nameEn: 'E-Bikes',
        nameZh: '电动车',
        descAr: 'تأجير دراجات وسكوتر كهربائي.',
        descEn: 'E-bike and e-scooter rental.',
        descZh: '电动自行车与滑板车租赁。',
        priceAr: 'من 5$/يوم',
        priceEn: 'From $5/day',
        priceZh: '每天$5起',
      },
      {
        id: 'boats',
        icon: 'directions_boat',
        sortOrder: 7,
        nameAr: 'قوارب',
        nameEn: 'Boats',
        nameZh: '船运',
        descAr: 'عبّارات ونقل بحري.',
        descEn: 'Ferries and sea transport.',
        descZh: '渡轮及海运出行。',
        priceAr: 'عرض حسب الطلب',
        priceEn: 'Quote by route',
        priceZh: '按航线报价',
      },
      {
        id: 'bicycles',
        icon: 'pedal_bike',
        sortOrder: 8,
        nameAr: 'دراجات',
        nameEn: 'Bicycles',
        nameZh: '自行车',
        descAr: 'تأجير دراجات يومية.',
        descEn: 'Daily bicycle rental.',
        descZh: '日租自行车。',
        priceAr: 'من 3$/يوم',
        priceEn: 'From $3/day',
        priceZh: '每天$3起',
      },
      {
        id: 'scooters',
        icon: 'two_wheeler',
        sortOrder: 9,
        nameAr: 'سكوترات',
        nameEn: 'Scooters',
        nameZh: '滑板车',
        descAr: 'سكوتر مشاركة وتأجير قصير.',
        descEn: 'Shared and short-term scooter rental.',
        descZh: '共享及短租滑板车。',
        priceAr: 'من 4$/يوم',
        priceEn: 'From $4/day',
        priceZh: '每天$4起',
      },
      {
        id: 'car-rental',
        icon: 'directions_car',
        sortOrder: 10,
        nameAr: 'تأجير سيارات',
        nameEn: 'Car Rental',
        nameZh: '租车',
        descAr: 'تأجير سيارات يومي أو شهري.',
        descEn: 'Daily or monthly car rental.',
        descZh: '按日或按月租车。',
        priceAr: 'حسب الطلب',
        priceEn: 'On request',
        priceZh: '按需报价',
      },
      {
        id: 'private-transfer',
        icon: 'airport_shuttle',
        sortOrder: 11,
        nameAr: 'نقل خاص',
        nameEn: 'Private Transfer',
        nameZh: '专车接送',
        descAr: 'نقل خاص من وإلى المطار أو المدينة.',
        descEn: 'Private airport and city transfers.',
        descZh: '机场与市区专车接送。',
        priceAr: 'حسب الطلب',
        priceEn: 'On request',
        priceZh: '按需报价',
      },
    ],
  },
  {
    slug: 'travel',
    icon: 'tourism',
    colorKey: 'travel',
    sortOrder: 3,
    nameAr: 'سياحة وسفر',
    nameEn: 'Travel',
    nameZh: '旅游出行',
    descAr: 'برامج سياحية وتأشيرات وتأمين سفر.',
    descEn: 'Tours, visas, and travel insurance.',
    descZh: '旅游套餐、签证与旅行保险。',
    priceAr: 'من 105¥',
    priceEn: 'From ¥105',
    priceZh: '¥105起',
    countries: [],
    subs: [
      {
        id: 'hotels',
        icon: 'hotel',
        sortOrder: 0,
        nameAr: 'فنادق سياحية',
        nameEn: 'Hotels',
        nameZh: '旅游酒店',
        descAr: 'فنادق لرحلات السياحة والعطلات.',
        descEn: 'Hotels for leisure and holiday trips.',
        descZh: '度假旅游酒店预订。',
        priceAr: 'من 320¥/ليلة',
        priceEn: 'From ¥320/night',
        priceZh: '每晚¥320起',
      },
      {
        id: 'tours',
        icon: 'tour',
        sortOrder: 1,
        nameAr: 'جولات سياحية',
        nameEn: 'Tours',
        nameZh: '旅行团',
        descAr: 'باقات جولات داخل الصين.',
        descEn: 'Tour packages across China.',
        descZh: '中国境内旅游套餐。',
        priceAr: 'من 700¥/يوم',
        priceEn: 'From ¥700/day',
        priceZh: '每天¥700起',
      },
      {
        id: 'guide',
        icon: 'person_pin',
        sortOrder: 2,
        nameAr: 'مرشد سياحي',
        nameEn: 'Tour Guide',
        nameZh: '导游',
        descAr: 'مرشدون ثنائيو اللغة.',
        descEn: 'Bilingual tour guides.',
        descZh: '双语导游服务。',
        priceAr: 'من 80$/يوم',
        priceEn: 'From $80/day',
        priceZh: '每天$80起',
      },
      {
        id: 'attractions',
        icon: 'attractions',
        sortOrder: 3,
        nameAr: 'معالم سياحية',
        nameEn: 'Attractions',
        nameZh: '景点门票',
        descAr: 'تذاكر المعالم والمتاحف.',
        descEn: 'Attraction and museum tickets.',
        descZh: '景点及博物馆门票。',
        priceAr: 'من 105¥',
        priceEn: 'From ¥105',
        priceZh: '¥105起',
      },
      {
        id: 'visa',
        icon: 'visa',
        sortOrder: 4,
        nameAr: 'تأشيرة',
        nameEn: 'Visa',
        nameZh: '签证',
        descAr: 'دعم تأشيرات السياحة والعمل.',
        descEn: 'Tourist and business visa support.',
        descZh: '旅游及商务签证协助。',
        priceAr: 'حسب الدولة · من 1100¥',
        priceEn: 'By country · from ¥1100',
        priceZh: '按国家 · ¥1100起',
      },
      {
        id: 'travel-insurance',
        icon: 'insurance',
        sortOrder: 5,
        nameAr: 'تأمين سفر',
        nameEn: 'Travel Insurance',
        nameZh: '旅行保险',
        descAr: 'تأمين طبي وسفر للرحلات.',
        descEn: 'Medical and travel coverage.',
        descZh: '旅行医疗保险。',
        priceAr: 'من 25$',
        priceEn: 'From $25',
        priceZh: '$25起',
      },
      {
        id: 'medical-tourism',
        icon: 'medical_services',
        sortOrder: 6,
        nameAr: 'سياحة طبية',
        nameEn: 'Medical Tourism',
        nameZh: '医疗旅游',
        descAr: 'علاج وإقامة طبية في الصين.',
        descEn: 'Treatment and medical stays in China.',
        descZh: '中国医疗旅游服务。',
        priceAr: 'عرض مخصص',
        priceEn: 'Custom quote',
        priceZh: '定制报价',
      },
      {
        id: 'religious-tourism',
        icon: 'mosque',
        sortOrder: 7,
        nameAr: 'سياحة دينية',
        nameEn: 'Religious Tourism',
        nameZh: '宗教旅游',
        descAr: 'برامج حج وعمرة وزيارات دينية.',
        descEn: 'Hajj, Umrah, and faith-based trips.',
        descZh: '朝觐及宗教朝圣行程。',
        priceAr: 'عرض مخصص',
        priceEn: 'Custom quote',
        priceZh: '定制报价',
      },
      {
        id: 'tourist-transport',
        icon: 'directions_bus',
        sortOrder: 8,
        nameAr: 'نقل سياحي',
        nameEn: 'Tourist Transport',
        nameZh: '旅游交通',
        descAr: 'نقل للمجموعات والجولات.',
        descEn: 'Group and tour transport.',
        descZh: '团队与行程交通。',
        priceAr: 'حسب الطلب',
        priceEn: 'On request',
        priceZh: '按需报价',
      },
    ],
  },
  {
    slug: 'healthcare',
    icon: 'local_hospital',
    colorKey: 'healthcare',
    sortOrder: 4,
    nameAr: 'رعاية صحية',
    nameEn: 'Healthcare',
    nameZh: '医疗健康',
    descAr: 'مستشفيات وعيادات وصيدليات في الصين.',
    descEn: 'Hospitals, clinics, and pharmacies in China.',
    descZh: '中国医院、诊所与药房服务。',
    priceAr: 'من 30$',
    priceEn: 'From $30',
    priceZh: '$30起',
    countries: ["CN"],
    subs: [
      {
        id: 'hospitals',
        icon: 'local_hospital',
        sortOrder: 0,
        nameAr: 'مستشفيات',
        nameEn: 'Hospitals',
        nameZh: '医院',
        descAr: 'حجز مواعيد ومستشفيات معتمدة.',
        descEn: 'Appointments at accredited hospitals.',
        descZh: '正规医院预约挂号。',
        priceAr: 'من 30$',
        priceEn: 'From $30',
        priceZh: '每月$30起',
      },
      {
        id: 'pharmacies',
        icon: 'local_pharmacy',
        sortOrder: 1,
        nameAr: 'صيدليات',
        nameEn: 'Pharmacies',
        nameZh: '药房',
        descAr: 'صيدليات وتوصيل أدوية.',
        descEn: 'Pharmacies and medicine delivery.',
        descZh: '药房及药品配送。',
        priceAr: 'من 50$',
        priceEn: 'From $50',
        priceZh: '$50起',
      },
      {
        id: 'clinics',
        icon: 'medical_information',
        sortOrder: 2,
        nameAr: 'عيادات',
        nameEn: 'Clinics',
        nameZh: '诊所',
        descAr: 'عيادات عامة وتخصصية.',
        descEn: 'General and specialist clinics.',
        descZh: '全科及专科诊所。',
        priceAr: 'غير محدد',
        priceEn: 'TBD',
        priceZh: '待定',
      },
      {
        id: 'telemedicine',
        icon: 'video_call',
        sortOrder: 3,
        nameAr: 'طب عن بُعد',
        nameEn: 'Telemedicine',
        nameZh: '远程医疗',
        descAr: 'استشارة طبية عبر الفيديو.',
        descEn: 'Video medical consultations.',
        descZh: '视频远程问诊。',
        priceAr: 'من 30$',
        priceEn: 'From $30',
        priceZh: '每次$30起',
      },
      {
        id: 'labs',
        icon: 'science',
        sortOrder: 4,
        nameAr: 'مختبرات',
        nameEn: 'Labs',
        nameZh: '化验',
        descAr: 'فحوصات وتحاليل مخبرية.',
        descEn: 'Lab tests and diagnostics.',
        descZh: '医学检验与化验。',
        priceAr: 'من 25$',
        priceEn: 'From $25',
        priceZh: '每次$25起',
      },
      {
        id: 'dental',
        icon: 'dentistry',
        sortOrder: 5,
        nameAr: 'أسنان',
        nameEn: 'Dental',
        nameZh: '牙科',
        descAr: 'عيادات وعلاجات الأسنان.',
        descEn: 'Dental clinics and treatments.',
        descZh: '牙科诊疗服务。',
        priceAr: 'من 20$',
        priceEn: 'From $20',
        priceZh: '每次$20起',
      },
      {
        id: 'vet',
        icon: 'pets',
        sortOrder: 6,
        nameAr: 'بيطري',
        nameEn: 'Veterinary',
        nameZh: '宠物医疗',
        descAr: 'عيادات بيطرية للحيوانات الأليفة.',
        descEn: 'Vet clinics for pets.',
        descZh: '宠物兽医诊所。',
        priceAr: 'من 40$',
        priceEn: 'From $40',
        priceZh: '每次$40起',
      },
      {
        id: 'health-insurance',
        icon: 'health_and_safety',
        sortOrder: 7,
        nameAr: 'تأمين صحي',
        nameEn: 'Health Insurance',
        nameZh: '医疗保险',
        descAr: 'خيارات تأمين صحي للمقيمين والزوار.',
        descEn: 'Health cover for residents and visitors.',
        descZh: '居民与访客医疗保险。',
        priceAr: 'حسب الطلب',
        priceEn: 'On request',
        priceZh: '按需报价',
      },
      {
        id: 'ambulance',
        icon: 'emergency',
        sortOrder: 8,
        nameAr: 'إسعاف',
        nameEn: 'Ambulance',
        nameZh: '急救护送',
        descAr: 'تنسيق خدمات الإسعاف عند الحاجة.',
        descEn: 'Ambulance coordination when needed.',
        descZh: '按需协调急救护送。',
        priceAr: 'حسب الطلب',
        priceEn: 'On request',
        priceZh: '按需报价',
      },
    ],
  },
  {
    slug: 'food',
    icon: 'restaurant',
    colorKey: 'food',
    sortOrder: 5,
    nameAr: 'طعام ومشروبات',
    nameEn: 'Food',
    nameZh: '餐饮美食',
    descAr: 'مطاعم وسوبرماركت وتوصيل طعام.',
    descEn: 'Restaurants, supermarkets, and food delivery.',
    descZh: '餐厅、超市与外卖配送。',
    priceAr: 'من 10$',
    priceEn: 'From $10',
    priceZh: '$10起',
    countries: [],
    subs: [
      {
        id: 'arabic',
        icon: 'restaurant',
        sortOrder: 0,
        nameAr: 'مأكولات عربية',
        nameEn: 'Arabic Cuisine',
        nameZh: '阿拉伯餐',
        descAr: 'مطاعم عربية أصيلة.',
        descEn: 'Authentic Arabic restaurants.',
        descZh: '正宗阿拉伯餐厅。',
        priceAr: 'من 10$',
        priceEn: 'From $10',
        priceZh: '每餐$10起',
      },
      {
        id: 'chinese',
        icon: 'ramen_dining',
        sortOrder: 1,
        nameAr: 'مأكولات صينية',
        nameEn: 'Chinese Cuisine',
        nameZh: '中餐',
        descAr: 'مطاعم صينية محلية ومشهورة.',
        descEn: 'Local and famous Chinese restaurants.',
        descZh: '本地及知名中餐厅。',
        priceAr: 'من 8$',
        priceEn: 'From $8',
        priceZh: '$8起',
      },
      {
        id: 'asian',
        icon: 'rice_bowl',
        sortOrder: 2,
        nameAr: 'مأكولات آسيوية',
        nameEn: 'Asian Cuisine',
        nameZh: '亚洲餐',
        descAr: 'ياباني وكوري وتايلندي وغيرها.',
        descEn: 'Japanese, Korean, Thai, and more.',
        descZh: '日料、韩餐、泰餐等。',
        priceAr: 'من 10$',
        priceEn: 'From $10',
        priceZh: '$10起',
      },
      {
        id: 'fastfood',
        icon: 'fastfood',
        sortOrder: 3,
        nameAr: 'وجبات سريعة',
        nameEn: 'Fast Food',
        nameZh: '快餐',
        descAr: 'برجر وبيتزا وسلاسل عالمية.',
        descEn: 'Burgers, pizza, and global chains.',
        descZh: '汉堡、披萨及连锁快餐。',
        priceAr: 'من 5$',
        priceEn: 'From $5',
        priceZh: '$5起',
      },
      {
        id: 'sweets',
        icon: 'cake',
        sortOrder: 4,
        nameAr: 'حلويات',
        nameEn: 'Sweets',
        nameZh: '甜品',
        descAr: 'حلويات عربية وشرقية وغربية.',
        descEn: 'Arabic, Asian, and Western desserts.',
        descZh: '阿拉伯、亚洲及西式甜品。',
        priceAr: 'من 6$',
        priceEn: 'From $6',
        priceZh: '$6起',
      },
      {
        id: 'coffee',
        icon: 'local_cafe',
        sortOrder: 5,
        nameAr: 'قهوة ومشروبات',
        nameEn: 'Coffee & Drinks',
        nameZh: '咖啡饮品',
        descAr: 'مقاهي ومشروبات باردة وساخنة.',
        descEn: 'Cafés and hot/cold beverages.',
        descZh: '咖啡馆及冷热饮品。',
        priceAr: 'من 4$',
        priceEn: 'From $4',
        priceZh: '$4起',
      },
      {
        id: 'supermarket',
        icon: 'shopping_cart',
        sortOrder: 6,
        nameAr: 'سوبرماركت',
        nameEn: 'Supermarket',
        nameZh: '超市',
        descAr: 'بقالة ومنتجات يومية.',
        descEn: 'Groceries and daily essentials.',
        descZh: '日用品及生鲜超市。',
        priceAr: 'غير محدد',
        priceEn: 'TBD',
        priceZh: '待定',
      },
      {
        id: 'yemeni',
        icon: 'restaurant_menu',
        sortOrder: 7,
        nameAr: 'مأكولات يمنية',
        nameEn: 'Yemeni Cuisine',
        nameZh: '也门餐',
        descAr: 'مندي وزربيان وأطباق يمنية أصيلة.',
        descEn: 'Mandi, zurbian, and authentic Yemeni dishes.',
        descZh: '曼迪、也门传统美食。',
        priceAr: 'من 10$',
        priceEn: 'From $10',
        priceZh: '$10起',
      },
      {
        id: 'food-delivery',
        icon: 'delivery_dining',
        sortOrder: 8,
        nameAr: 'توصيل طلبات',
        nameEn: 'Food Delivery',
        nameZh: '外卖配送',
        descAr: 'توصيل وجبات ومشتريات غذائية.',
        descEn: 'Meal and grocery delivery.',
        descZh: '餐食与食材配送。',
        priceAr: 'حسب الطلب',
        priceEn: 'On request',
        priceZh: '按需报价',
      },
    ],
  },
  {
    slug: 'shopping',
    icon: 'shopping_bag',
    colorKey: 'shopping',
    sortOrder: 6,
    nameAr: 'تسوق',
    nameEn: 'Shopping',
    nameZh: '购物',
    descAr: 'مصانع ومنتجات جديدة ومستعملة.',
    descEn: 'Factories, new and used products.',
    descZh: '工厂直采、新品与二手商品。',
    priceAr: 'استشارة مجانية',
    priceEn: 'Consult free',
    priceZh: '免费咨询',
    countries: [],
    subs: [
      {
        id: 'factories',
        icon: 'factory',
        sortOrder: 0,
        nameAr: 'مصانع',
        nameEn: 'Factories',
        nameZh: '工厂',
        descAr: 'زيارة مصانع وتوريد مباشر.',
        descEn: 'Factory visits and direct sourcing.',
        descZh: '工厂参观与直采。',
        priceAr: 'من 99$',
        priceEn: 'From $99',
        priceZh: '$99起',
      },
      {
        id: 'products',
        icon: 'inventory',
        sortOrder: 1,
        nameAr: 'منتجات',
        nameEn: 'Products',
        nameZh: '商品',
        descAr: 'منتجات جديدة بالجملة والتجزئة.',
        descEn: 'New wholesale and retail products.',
        descZh: '批发零售新品。',
        priceAr: 'عرض حسب الطلب',
        priceEn: 'Quote by order',
        priceZh: '按订单报价',
      },
      {
        id: 'used',
        icon: 'recycling',
        sortOrder: 2,
        nameAr: 'مستعمل',
        nameEn: 'Used Goods',
        nameZh: '二手',
        descAr: 'بضائع مستعملة ومعاد تجديدها.',
        descEn: 'Used and refurbished goods.',
        descZh: '二手及翻新商品。',
        priceAr: 'غير محدد',
        priceEn: 'TBD',
        priceZh: '待定',
      },
      {
        id: 'electronics',
        icon: 'devices',
        sortOrder: 3,
        nameAr: 'إلكترونيات',
        nameEn: 'Electronics',
        nameZh: '电子产品',
        descAr: 'هواتف وأجهزة وإكسسوارات.',
        descEn: 'Phones, devices, and accessories.',
        descZh: '手机、设备及配件。',
        priceAr: 'من 20$',
        priceEn: 'From $20',
        priceZh: '$20起',
      },
      {
        id: 'clothing',
        icon: 'checkroom',
        sortOrder: 4,
        nameAr: 'ملابس',
        nameEn: 'Clothing',
        nameZh: '服装',
        descAr: 'أزياء جملة وتجزئة.',
        descEn: 'Wholesale and retail fashion.',
        descZh: '服装批发与零售。',
        priceAr: 'من 15$',
        priceEn: 'From $15',
        priceZh: '$15起',
      },
      {
        id: 'furniture',
        icon: 'chair',
        sortOrder: 5,
        nameAr: 'أثاث',
        nameEn: 'Furniture',
        nameZh: '家具',
        descAr: 'أثاث منزلي ومكتبي.',
        descEn: 'Home and office furniture.',
        descZh: '家居及办公家具。',
        priceAr: 'من 50$',
        priceEn: 'From $50',
        priceZh: '$50起',
      },
      {
        id: 'beauty',
        icon: 'spa',
        sortOrder: 6,
        nameAr: 'مكياج وعطور',
        nameEn: 'Beauty & Fragrance',
        nameZh: '美妆香水',
        descAr: 'مكياج وعطور ومستحضرات تجميل.',
        descEn: 'Makeup, fragrance, and beauty products.',
        descZh: '美妆、香水与护理产品。',
        priceAr: 'حسب الطلب',
        priceEn: 'On request',
        priceZh: '按需报价',
      },
      {
        id: 'groceries',
        icon: 'local_grocery_store',
        sortOrder: 7,
        nameAr: 'مواد غذائية',
        nameEn: 'Groceries',
        nameZh: '食品物资',
        descAr: 'توريد مواد غذائية بالجملة أو التجزئة.',
        descEn: 'Wholesale or retail grocery supply.',
        descZh: '食品批发或零售供应。',
        priceAr: 'حسب الطلب',
        priceEn: 'On request',
        priceZh: '按需报价',
      },
    ],
  },
  {
    slug: 'education',
    icon: 'school',
    colorKey: 'education',
    sortOrder: 7,
    nameAr: 'تعليم واستشارات',
    nameEn: 'Education',
    nameZh: '教育培训',
    descAr: 'لغة صينية ودراسة عن بُعد واستشارات.',
    descEn: 'Chinese language, remote study, and consulting.',
    descZh: '中文学习、远程教育与咨询服务。',
    priceAr: 'من 49$',
    priceEn: 'From $49',
    priceZh: '$49起',
    countries: [],
    subs: [
      {
        id: 'chinese-lang',
        icon: 'translate',
        sortOrder: 0,
        nameAr: 'لغة صينية',
        nameEn: 'Chinese Language',
        nameZh: '中文学习',
        descAr: 'دورات ومعلمون للغة الصينية.',
        descEn: 'Chinese language courses and tutors.',
        descZh: '中文课程与辅导。',
        priceAr: 'من 49$/شهر',
        priceEn: 'From $49/mo',
        priceZh: '每月$49起',
      },
      {
        id: 'remote-study',
        icon: 'laptop',
        sortOrder: 1,
        nameAr: 'دراسة عن بُعد',
        nameEn: 'Remote Study',
        nameZh: '远程学习',
        descAr: 'برامج دراسية عبر الإنترنت.',
        descEn: 'Online study programs.',
        descZh: '在线学习项目。',
        priceAr: 'من 99$',
        priceEn: 'From $99',
        priceZh: '$99起',
      },
      {
        id: 'legal',
        icon: 'gavel',
        sortOrder: 2,
        nameAr: 'استشارات قانونية',
        nameEn: 'Legal',
        nameZh: '法律咨询',
        descAr: 'عقود وامتثال ودعم قانوني.',
        descEn: 'Contracts, compliance, and legal support.',
        descZh: '合同、合规与法律支持。',
        priceAr: 'من 199$',
        priceEn: 'From $199',
        priceZh: '$199起',
      },
      {
        id: 'property-consult',
        icon: 'real_estate_agent',
        sortOrder: 3,
        nameAr: 'استشارات عقارية',
        nameEn: 'Property Consulting',
        nameZh: '房产咨询',
        descAr: 'تقييم وشراء عقارات بإرشاد.',
        descEn: 'Property evaluation and purchase guidance.',
        descZh: '房产评估与购置咨询。',
        priceAr: 'استشارة مجانية',
        priceEn: 'Consult free',
        priceZh: '免费咨询',
      },
      {
        id: 'education',
        icon: 'school',
        sortOrder: 4,
        nameAr: 'تعليم أكاديمي',
        nameEn: 'Education',
        nameZh: '学历教育',
        descAr: 'جامعات ومنح وقبول دراسي.',
        descEn: 'Universities, scholarships, and admissions.',
        descZh: '大学申请与奖学金。',
        priceAr: 'من 150$',
        priceEn: 'From $150',
        priceZh: '$150起',
      },
      {
        id: 'admin',
        icon: 'admin_panel_settings',
        sortOrder: 5,
        nameAr: 'خدمات إدارية',
        nameEn: 'Admin Services',
        nameZh: '行政服务',
        descAr: 'تنسيق معاملات ووثائق رسمية.',
        descEn: 'Official paperwork coordination.',
        descZh: '官方文件与事务协调。',
        priceAr: 'من 79$',
        priceEn: 'From $79',
        priceZh: '$79起',
      },
      {
        id: 'social',
        icon: 'groups',
        sortOrder: 6,
        nameAr: 'خدمات اجتماعية',
        nameEn: 'Social Services',
        nameZh: '社会服务',
        descAr: 'دعم مجتمعي وتكيف ثقافي.',
        descEn: 'Community support and cultural adaptation.',
        descZh: '社区支持与文化适应。',
        priceAr: 'غير محدد',
        priceEn: 'TBD',
        priceZh: '待定',
      },
      {
        id: 'scholarships',
        icon: 'school',
        sortOrder: 7,
        nameAr: 'منح دراسية',
        nameEn: 'Scholarships',
        nameZh: '奖学金',
        descAr: 'إرشاد المنح ومسارات الدراسة.',
        descEn: 'Scholarship and study pathway guidance.',
        descZh: '奖学金与留学路径指导。',
        priceAr: 'حسب الطلب',
        priceEn: 'On request',
        priceZh: '按需报价',
      },
      {
        id: 'training-courses',
        icon: 'workspace_premium',
        sortOrder: 8,
        nameAr: 'دورات تدريبية',
        nameEn: 'Training Courses',
        nameZh: '培训课程',
        descAr: 'دورات مهنية وتدريبية.',
        descEn: 'Professional training courses.',
        descZh: '职业与技能培训课程。',
        priceAr: 'حسب الطلب',
        priceEn: 'On request',
        priceZh: '按需报价',
      },
    ],
  },
  {
    slug: 'logistics',
    icon: 'local_shipping',
    colorKey: 'logistics',
    sortOrder: 8,
    nameAr: 'لوجستيات وشحن',
    nameEn: 'Logistics',
    nameZh: '物流运输',
    descAr: 'توصيل وشحن دولي وجمارك وتخزين.',
    descEn: 'Delivery, international shipping, customs, and storage.',
    descZh: '配送、国际货运、清关与仓储。',
    priceAr: 'عرض حسب الوزن',
    priceEn: 'Quote by weight',
    priceZh: '按重量报价',
    countries: [],
    subs: [
      {
        id: 'delivery',
        icon: 'delivery',
        sortOrder: 0,
        nameAr: 'توصيل محلي',
        nameEn: 'Delivery',
        nameZh: '本地配送',
        descAr: 'توصيل داخل المدن والمناطق.',
        descEn: 'Local city and regional delivery.',
        descZh: '同城及区域配送。',
        priceAr: 'من 8$',
        priceEn: 'From $8',
        priceZh: '$8起',
      },
      {
        id: 'intl-shipping',
        icon: 'flight_takeoff',
        sortOrder: 1,
        nameAr: 'شحن دولي',
        nameEn: 'International Shipping',
        nameZh: '国际货运',
        descAr: 'شحن بحري وجوي للبضائع.',
        descEn: 'Sea and air freight for goods.',
        descZh: '海运及空运国际货运。',
        priceAr: 'عرض حسب الوزن',
        priceEn: 'Quote by weight',
        priceZh: '按重量报价',
      },
      {
        id: 'customs',
        icon: 'assignment',
        sortOrder: 2,
        nameAr: 'جمارك',
        nameEn: 'Customs',
        nameZh: '清关',
        descAr: 'تخليص جمركي واستيراد وتصدير.',
        descEn: 'Customs clearance for import/export.',
        descZh: '进出口清关服务。',
        priceAr: 'من 50$',
        priceEn: 'From $50',
        priceZh: '$50起',
      },
      {
        id: 'moving',
        icon: 'moving',
        sortOrder: 3,
        nameAr: 'نقل عفش',
        nameEn: 'Moving',
        nameZh: '搬家',
        descAr: 'نقل أثاث وعفش منزلي.',
        descEn: 'Household furniture moving.',
        descZh: '家具搬家服务。',
        priceAr: 'من 80$',
        priceEn: 'From $80',
        priceZh: '$80起',
      },
      {
        id: 'storage',
        icon: 'warehouse',
        sortOrder: 4,
        nameAr: 'تخزين',
        nameEn: 'Storage',
        nameZh: '仓储',
        descAr: 'مستودعات تخزين قصيرة وطويلة المدى.',
        descEn: 'Short and long-term warehouse storage.',
        descZh: '短期及长期仓储。',
        priceAr: 'من 53$/شهر',
        priceEn: 'From $53/mo',
        priceZh: '每月$53起',
      },
      {
        id: 'car-shipping',
        icon: 'directions_car',
        sortOrder: 5,
        nameAr: 'شحن سيارات',
        nameEn: 'Car Shipping',
        nameZh: '车辆运输',
        descAr: 'شحن السيارات داخل الصين وخارجها.',
        descEn: 'Vehicle shipping in and out of China.',
        descZh: '中国境内外车辆运输。',
        priceAr: 'حسب الطلب',
        priceEn: 'On request',
        priceZh: '按需报价',
      },
      {
        id: 'shipment-tracking',
        icon: 'share_location',
        sortOrder: 6,
        nameAr: 'تتبع شحنة',
        nameEn: 'Shipment Tracking',
        nameZh: '物流追踪',
        descAr: 'متابعة حالة الشحنة خطوة بخطوة.',
        descEn: 'Track shipment status step by step.',
        descZh: '逐步跟踪货运状态。',
        priceAr: 'حسب الطلب',
        priceEn: 'On request',
        priceZh: '按需报价',
      },
    ],
  },
  {
    slug: 'government',
    icon: 'account_balance',
    colorKey: 'government',
    sortOrder: 9,
    nameAr: 'خدمات حكومية',
    nameEn: 'Government',
    nameZh: '政务服务',
    descAr: 'جوازات وإقامة وتأشيرات ووثائق رسمية.',
    descEn: 'Passports, residence, visas, and official documents.',
    descZh: '护照、居留、签证及官方文件。',
    priceAr: 'من 300¥',
    priceEn: 'From ¥300',
    priceZh: '¥300起',
    countries: [],
    subs: [
      {
        id: 'passports',
        icon: 'badge',
        sortOrder: 0,
        nameAr: 'جوازات سفر',
        nameEn: 'Passports',
        nameZh: '护照',
        descAr: 'تجديد وإصدار جوازات السفر.',
        descEn: 'Passport renewal and issuance.',
        descZh: '护照办理与续签。',
        priceAr: 'من 99$',
        priceEn: 'From $99',
        priceZh: '$99起',
      },
      {
        id: 'residence',
        icon: 'home_work',
        sortOrder: 1,
        nameAr: 'إقامة',
        nameEn: 'Residence',
        nameZh: '居留',
        descAr: 'تصاريح إقامة وتجديدها.',
        descEn: 'Residence permits and renewals.',
        descZh: '居留许可及续签。',
        priceAr: '2500¥ (إيوو)',
        priceEn: '¥2500 (Yiwu)',
        priceZh: '义乌¥2500',
      },
      {
        id: 'visas',
        icon: 'visa',
        sortOrder: 2,
        nameAr: 'تأشيرات',
        nameEn: 'Visas',
        nameZh: '签证',
        descAr: 'تأشيرات دخول وتمديد الإقامة.',
        descEn: 'Entry visas and stay extensions.',
        descZh: '入境签证及延期。',
        priceAr: 'حسب الدولة · من 950¥',
        priceEn: 'By country · from ¥950',
        priceZh: '按国家 · ¥950起',
      },
      {
        id: 'documents',
        icon: 'description',
        sortOrder: 3,
        nameAr: 'وثائق رسمية',
        nameEn: 'Documents',
        nameZh: '官方文件',
        descAr: 'تصديق وترجمة وتوثيق.',
        descEn: 'Attestation, translation, and notarization.',
        descZh: '认证、翻译与公证。',
        priceAr: 'ترجمة من 300¥',
        priceEn: 'Translation from ¥300',
        priceZh: '翻译¥300起',
      },
      {
        id: 'gov-services',
        icon: 'domain',
        sortOrder: 4,
        nameAr: 'خدمات حكومية عامة',
        nameEn: 'Government Services',
        nameZh: '综合政务',
        descAr: 'تنسيق معاملات الجهات الرسمية.',
        descEn: 'Coordination with government offices.',
        descZh: '政府部门事务协调。',
        priceAr: 'من 79$',
        priceEn: 'From $79',
        priceZh: '$79起',
      },
      {
        id: 'document-attestation',
        icon: 'verified',
        sortOrder: 5,
        nameAr: 'تصديق وثائق',
        nameEn: 'Document Attestation',
        nameZh: '文件认证',
        descAr: 'تصديق الوثائق الرسمية.',
        descEn: 'Official document attestation.',
        descZh: '官方文件认证。',
        priceAr: 'حسب الطلب',
        priceEn: 'On request',
        priceZh: '按需报价',
      },
      {
        id: 'licenses',
        icon: 'badge',
        sortOrder: 6,
        nameAr: 'تراخيص',
        nameEn: 'Licenses',
        nameZh: '许可证',
        descAr: 'دعم استخراج التراخيص.',
        descEn: 'License application support.',
        descZh: '协助办理许可证。',
        priceAr: 'حسب الطلب',
        priceEn: 'On request',
        priceZh: '按需报价',
      },
      {
        id: 'tax-services',
        icon: 'receipt_long',
        sortOrder: 7,
        nameAr: 'خدمات ضرائب',
        nameEn: 'Tax Services',
        nameZh: '税务服务',
        descAr: 'إجراءات ودعم ضريبي.',
        descEn: 'Tax procedures and support.',
        descZh: '税务手续与支持。',
        priceAr: 'حسب الطلب',
        priceEn: 'On request',
        priceZh: '按需报价',
      },
      {
        id: 'social-insurance',
        icon: 'health_and_safety',
        sortOrder: 8,
        nameAr: 'تأمينات اجتماعية',
        nameEn: 'Social Insurance',
        nameZh: '社会保险',
        descAr: 'دعم التأمينات الاجتماعية.',
        descEn: 'Social insurance support.',
        descZh: '社会保险办理协助。',
        priceAr: 'حسب الطلب',
        priceEn: 'On request',
        priceZh: '按需报价',
      },
    ],
  },
  {
    slug: 'business',
    icon: 'work',
    colorKey: 'business',
    sortOrder: 10,
    nameAr: 'أعمال وتقنية',
    nameEn: 'Business',
    nameZh: '商务科技',
    descAr: 'تسويق وبرمجة وتصميم ومحاسبة واستشارات.',
    descEn: 'Marketing, programming, design, accounting, and consulting.',
    descZh: '营销、编程、设计、会计与咨询。',
    priceAr: 'من 99$',
    priceEn: 'From $99',
    priceZh: '$99起',
    countries: [],
    subs: [
      {
        id: 'marketing',
        icon: 'campaign',
        sortOrder: 0,
        nameAr: 'تسويق',
        nameEn: 'Marketing',
        nameZh: '市场营销',
        descAr: 'WeChat / Douyin / إعلانات رقمية.',
        descEn: 'WeChat / Douyin / digital ads.',
        descZh: '微信/抖音/数字广告投放。',
        priceAr: 'من 150$',
        priceEn: 'From $150',
        priceZh: '$150起',
      },
      {
        id: 'programming',
        icon: 'code',
        sortOrder: 1,
        nameAr: 'برمجة',
        nameEn: 'Programming',
        nameZh: '软件开发',
        descAr: 'تطبيقات ومواقع وأنظمة مخصصة.',
        descEn: 'Custom apps, websites, and systems.',
        descZh: '定制应用、网站与系统。',
        priceAr: 'من 299$',
        priceEn: 'From $299',
        priceZh: '$299起',
      },
      {
        id: 'design',
        icon: 'palette',
        sortOrder: 2,
        nameAr: 'تصميم',
        nameEn: 'Design',
        nameZh: '设计',
        descAr: 'هوية بصرية وتصميم واجهات.',
        descEn: 'Branding and UI/UX design.',
        descZh: '品牌视觉与界面设计。',
        priceAr: 'من 120$',
        priceEn: 'From $120',
        priceZh: '$120起',
      },
      {
        id: 'accounting',
        icon: 'calculate',
        sortOrder: 3,
        nameAr: 'محاسبة',
        nameEn: 'Accounting',
        nameZh: '会计',
        descAr: 'محاسبة وضرائب وتقارير مالية.',
        descEn: 'Accounting, tax, and financial reports.',
        descZh: '会计、税务与财务报表。',
        priceAr: 'من 99$',
        priceEn: 'From $99',
        priceZh: '$99起',
      },
      {
        id: 'business-consult',
        icon: 'biz',
        sortOrder: 4,
        nameAr: 'استشارات أعمال',
        nameEn: 'Business Consulting',
        nameZh: '商务咨询',
        descAr: 'توريد واجتماعات ودعم تشغيلي.',
        descEn: 'Sourcing, meetings, and ops support.',
        descZh: '采购、会议与运营支持。',
        priceAr: 'من 99$',
        priceEn: 'From $99',
        priceZh: '$99起',
      },
      {
        id: 'company-registration',
        icon: 'domain',
        sortOrder: 5,
        nameAr: 'تسجيل شركات',
        nameEn: 'Company Registration',
        nameZh: '公司注册',
        descAr: 'تسجيل وهيكلة الشركة في الصين.',
        descEn: 'Register and structure a company in China.',
        descZh: '在中国注册与搭建公司。',
        priceAr: 'من 3500¥ (إيوو)',
        priceEn: 'From ¥3500 (Yiwu)',
        priceZh: '义乌¥3500起',
      },
      {
        id: 'company-hk',
        icon: 'domain',
        sortOrder: 20,
        nameAr: 'شركة هونغ كونغ',
        nameEn: 'Hong Kong Company',
        nameZh: '香港公司注册',
        descAr: 'تسجيل شركة هونغ كونغ · رمز شخصي · تدقيق سنوي حسب الاتفاق.',
        descEn: 'HK company registration · personal code · annual audit by agreement.',
        descZh: '香港公司注册、个人码、年度审计（另议）。',
        priceAr: 'من 2000¥ · تسجيل 8000¥',
        priceEn: 'From ¥2000 · reg. ¥8000',
        priceZh: '¥2000起 · 注册¥8000',
      },
      {
        id: 'company-uk',
        icon: 'domain',
        sortOrder: 21,
        nameAr: 'شركة بريطانية',
        nameEn: 'UK Company',
        nameZh: '英国公司注册',
        descAr: 'تسجيل شركة بريطانية · رمز شخصي · حساب دولار · تدقيق سنوي.',
        descEn: 'UK company · personal code · USD account · annual audit.',
        descZh: '英国公司、个人码、美元账户、年审。',
        priceAr: 'من 1500¥ · تسجيل 6000¥',
        priceEn: 'From ¥1500 · reg. ¥6000',
        priceZh: '¥1500起 · 注册¥6000',
      },
      {
        id: 'company-yiwu',
        icon: 'domain',
        sortOrder: 22,
        nameAr: 'شركة إيوو / فوشان',
        nameEn: 'Yiwu / Foshan Company',
        nameZh: '义乌/佛山公司',
        descAr: 'تسجيل · حساب مؤسسة · محاسبة وكالة · إقامة · مكتب.',
        descEn: 'Registration · enterprise account · agency accounting · residence · office.',
        descZh: '注册、对公账户、代理记账、居留、办公室。',
        priceAr: 'من 1000¥ · تسجيل 3500¥',
        priceEn: 'From ¥1000 · reg. ¥3500',
        priceZh: '¥1000起 · 注册¥3500',
      },
      {
        id: 'company-guangzhou',
        icon: 'domain',
        sortOrder: 23,
        nameAr: 'شركة قوانغتشو',
        nameEn: 'Guangzhou Company',
        nameZh: '广州公司注册',
        descAr: 'تسجيل · محاسبة وكالة · تأشيرة/دعوة عمل · ترجمة.',
        descEn: 'Registration · agency accounting · work visa/invitation · translation.',
        descZh: '注册、代理记账、工签/邀请函、翻译。',
        priceAr: 'من 1000¥ · تسجيل 5000¥',
        priceEn: 'From ¥1000 · reg. ¥5000',
        priceZh: '¥1000起 · 注册¥5000',
      },
      {
        id: 'trademarks',
        icon: 'verified',
        sortOrder: 6,
        nameAr: 'علامات تجارية',
        nameEn: 'Trademarks',
        nameZh: '商标注册',
        descAr: 'تسجيل وحماية العلامة التجارية.',
        descEn: 'Trademark registration and protection.',
        descZh: '商标注册与保护。',
        priceAr: 'حسب الطلب',
        priceEn: 'On request',
        priceZh: '按需报价',
      },
      {
        id: 'legal-translation',
        icon: 'translate',
        sortOrder: 7,
        nameAr: 'ترجمة قانونية',
        nameEn: 'Legal Translation',
        nameZh: '法律翻译',
        descAr: 'ترجمة وثائق قانونية معتمدة.',
        descEn: 'Certified legal document translation.',
        descZh: '法律文件认证翻译。',
        priceAr: 'حسب الطلب',
        priceEn: 'On request',
        priceZh: '按需报价',
      },
      {
        id: 'contract-notarization',
        icon: 'gavel',
        sortOrder: 8,
        nameAr: 'توثيق عقود',
        nameEn: 'Contract Notarization',
        nameZh: '合同公证',
        descAr: 'توثيق العقود والاتفاقيات.',
        descEn: 'Notarize contracts and agreements.',
        descZh: '合同与协议公证。',
        priceAr: 'حسب الطلب',
        priceEn: 'On request',
        priceZh: '按需报价',
      },
      {
        id: 'tax-consulting',
        icon: 'calculate',
        sortOrder: 9,
        nameAr: 'استشارات ضريبية',
        nameEn: 'Tax Consulting',
        nameZh: '税务咨询',
        descAr: 'استشارة ضريبية للأفراد والشركات.',
        descEn: 'Tax advice for individuals and companies.',
        descZh: '个人与企业税务咨询。',
        priceAr: 'حسب الطلب',
        priceEn: 'On request',
        priceZh: '按需报价',
      },
      {
        id: 'quality-inspection',
        icon: 'fact_check',
        sortOrder: 10,
        nameAr: 'فحص جودة',
        nameEn: 'Quality Inspection',
        nameZh: '质量检验',
        descAr: 'فحص جودة المنتجات قبل الشحن.',
        descEn: 'Product quality checks before shipping.',
        descZh: '发货前产品质量检验。',
        priceAr: 'حسب الطلب',
        priceEn: 'On request',
        priceZh: '按需报价',
      },
    ],
  },
];
