// Made by Dr Ali
// Inner service seed — synced from mobile catalog.

export type SubServiceSeedItem = {
  id: string;
  parentSlug: string;
  icon: string;
  sortOrder: number;
  nameAr: string;
  nameEn: string;
  nameZh: string;
  descAr: string;
  descEn: string;
  descZh: string;
  priceAr: string;
  priceEn: string;
  priceZh: string;
};

export const SUB_SERVICE_SEED: SubServiceSeedItem[] = [
  {
    id: 'hotels-book',
    parentSlug: 'hotels',
    icon: 'book',
    sortOrder: 0,
    nameAr: 'حجز فندق',
    nameEn: 'Book a hotel',
    nameZh: '',
    descAr: 'ابحث واحجز فندقاً لرحلة عملك.',
    descEn: 'Search and book a hotel for your business trip.',
    descZh: '',
    priceAr: 'من 45\\\$/ليلة',
    priceEn: 'From \\\$45/night',
    priceZh: '',
  },
  {
    id: 'hotels-gz',
    parentSlug: 'hotels',
    icon: 'location',
    sortOrder: 1,
    nameAr: 'فنادق قوانغتشو',
    nameEn: 'Guangzhou hotels',
    nameZh: '',
    descAr: 'خيارات فندقية قريبة من معارض قوانغتشو.',
    descEn: 'Hotel options near Guangzhou trade areas.',
    descZh: '',
    priceAr: 'عرض حسب التاريخ',
    priceEn: 'Quote by dates',
    priceZh: '',
  },
  {
    id: 'hotels-yw',
    parentSlug: 'hotels',
    icon: 'location',
    sortOrder: 2,
    nameAr: 'فنادق ييو',
    nameEn: 'Yiwu hotels',
    nameZh: '',
    descAr: 'إقامة قريبة من سوق ييو الدولي.',
    descEn: 'Stays near Yiwu International Trade City.',
    descZh: '',
    priceAr: 'عرض حسب التاريخ',
    priceEn: 'Quote by dates',
    priceZh: '',
  },
  {
    id: 'hotels-biz',
    parentSlug: 'hotels',
    icon: 'group',
    sortOrder: 3,
    nameAr: 'باقات إقامة أعمال',
    nameEn: 'Business stay packages',
    nameZh: '',
    descAr: 'فندق + نقل + مرشد للوفود التجارية.',
    descEn: 'Hotel + transfer + guide for trade delegations.',
    descZh: '',
    priceAr: 'عرض مخصص',
    priceEn: 'Custom quote',
    priceZh: '',
  },
  {
    id: 'flights-book',
    parentSlug: 'flights',
    icon: 'book',
    sortOrder: 4,
    nameAr: 'حجز تذكرة',
    nameEn: 'Book a flight',
    nameZh: '',
    descAr: 'مساعدة في حجز رحلات إلى الصين.',
    descEn: 'Assistance booking flights to China.',
    descZh: '',
    priceAr: 'مساعدة من 20\\\$',
    priceEn: 'Assist from \\\$20',
    priceZh: '',
  },
  {
    id: 'flights-change',
    parentSlug: 'flights',
    icon: 'doc',
    sortOrder: 5,
    nameAr: 'تعديل / إلغاء',
    nameEn: 'Change / cancel',
    nameZh: '',
    descAr: 'متابعة تغيير أو إلغاء التذاكر.',
    descEn: 'Follow up ticket changes or cancellations.',
    descZh: '',
    priceAr: 'حسب شركة الطيران',
    priceEn: 'Per airline policy',
    priceZh: '',
  },
  {
    id: 'flights-pickup',
    parentSlug: 'flights',
    icon: 'car',
    sortOrder: 6,
    nameAr: 'استقبال مطار',
    nameEn: 'Airport pickup',
    nameZh: '',
    descAr: 'ترتيب استقبال من المطار إلى الفندق.',
    descEn: 'Arrange airport pickup to your hotel.',
    descZh: '',
    priceAr: 'من 35\\\$',
    priceEn: 'From \\\$35',
    priceZh: '',
  },
  {
    id: 'flights-group',
    parentSlug: 'flights',
    icon: 'group',
    sortOrder: 7,
    nameAr: 'حجز جماعي',
    nameEn: 'Group booking',
    nameZh: '',
    descAr: 'تنسيق تذاكر للفرق والوفود.',
    descEn: 'Coordinate tickets for teams and delegations.',
    descZh: '',
    priceAr: 'عرض مخصص',
    priceEn: 'Custom quote',
    priceZh: '',
  },
  {
    id: 'visa-business',
    parentSlug: 'visa',
    icon: 'doc',
    sortOrder: 8,
    nameAr: 'تأشيرة عمل',
    nameEn: 'Business visa',
    nameZh: '',
    descAr: 'دعم تأشيرة عمل/زيارة للصين.',
    descEn: 'Business / visit visa support for China.',
    descZh: '',
    priceAr: 'من 120\\\$',
    priceEn: 'From \\\$120',
    priceZh: '',
  },
  {
    id: 'visa-tourist',
    parentSlug: 'visa',
    icon: 'doc',
    sortOrder: 9,
    nameAr: 'تأشيرة سياحة',
    nameEn: 'Tourist visa',
    nameZh: '',
    descAr: 'إرشاد مستندات تأشيرة السياحة.',
    descEn: 'Tourist visa document guidance.',
    descZh: '',
    priceAr: 'من 99\\\$',
    priceEn: 'From \\\$99',
    priceZh: '',
  },
  {
    id: 'visa-fast',
    parentSlug: 'visa',
    icon: 'speed',
    sortOrder: 0,
    nameAr: 'مسار سريع',
    nameEn: 'Fast track',
    nameZh: '',
    descAr: 'متابعة expedited عند توفرها.',
    descEn: 'Expedited follow-up when available.',
    descZh: '',
    priceAr: 'من 180\\\$',
    priceEn: 'From \\\$180',
    priceZh: '',
  },
  {
    id: 'visa-docs',
    parentSlug: 'visa',
    icon: 'consult',
    sortOrder: 1,
    nameAr: 'مراجعة مستندات',
    nameEn: 'Document review',
    nameZh: '',
    descAr: 'تدقيق الملف قبل التقديم.',
    descEn: 'Review your file before submission.',
    descZh: '',
    priceAr: 'من 49\\\$',
    priceEn: 'From \\\$49',
    priceZh: '',
  },
  {
    id: 'bank-open',
    parentSlug: 'bank',
    icon: 'book',
    sortOrder: 2,
    nameAr: 'فتح حساب',
    nameEn: 'Open account',
    nameZh: '',
    descAr: 'خطوات فتح حساب بنكي محلي.',
    descEn: 'Steps to open a local bank account.',
    descZh: '',
    priceAr: 'من 299\\\$',
    priceEn: 'From \\\$299',
    priceZh: '',
  },
  {
    id: 'bank-yw',
    parentSlug: 'bank',
    icon: 'location',
    sortOrder: 3,
    nameAr: 'فرع yiwu',
    nameEn: 'Yiwu branch',
    nameZh: '',
    descAr: 'إرشاد فتح حساب في yiwu.',
    descEn: 'Account opening guidance in Yiwu.',
    descZh: '',
    priceAr: 'من 299\\\$',
    priceEn: 'From \\\$299',
    priceZh: '',
  },
  {
    id: 'bank-gz',
    parentSlug: 'bank',
    icon: 'location',
    sortOrder: 4,
    nameAr: 'فرع قوانغتشو',
    nameEn: 'Guangzhou branch',
    nameZh: '',
    descAr: 'إرشاد فتح حساب في قوانغتشو.',
    descEn: 'Account opening guidance in Guangzhou.',
    descZh: '',
    priceAr: 'من 299\\\$',
    priceEn: 'From \\\$299',
    priceZh: '',
  },
  {
    id: 'bank-docs',
    parentSlug: 'bank',
    icon: 'doc',
    sortOrder: 5,
    nameAr: 'قائمة المستندات',
    nameEn: 'Document checklist',
    nameZh: '',
    descAr: 'ما تحتاجه قبل زيارة البنك.',
    descEn: 'What you need before visiting the bank.',
    descZh: '',
    priceAr: 'استشارة مجانية',
    priceEn: 'Free consult',
    priceZh: '',
  },
  {
    id: 'vip-full',
    parentSlug: 'vip',
    icon: 'book',
    sortOrder: 6,
    nameAr: 'برنامج VIP كامل',
    nameEn: 'Full VIP program',
    nameZh: '',
    descAr: 'استقبال، فندق، مصانع، مرشد.',
    descEn: 'Pickup, hotel, factories, dedicated guide.',
    descZh: '',
    priceAr: 'عرض مخصص',
    priceEn: 'Custom quote',
    priceZh: '',
  },
  {
    id: 'vip-factory',
    parentSlug: 'vip',
    icon: 'shop',
    sortOrder: 7,
    nameAr: 'زيارات مصانع',
    nameEn: 'Factory visits',
    nameZh: '',
    descAr: 'تنسيق جولات في yiwu / قوانغتشو.',
    descEn: 'Coordinate factory tours in Yiwu / Guangzhou.',
    descZh: '',
    priceAr: 'عرض مخصص',
    priceEn: 'Custom quote',
    priceZh: '',
  },
  {
    id: 'vip-pickup',
    parentSlug: 'vip',
    icon: 'car',
    sortOrder: 8,
    nameAr: 'استقبال VIP',
    nameEn: 'VIP pickup',
    nameZh: '',
    descAr: 'استقبال من المطار بمركبة مريحة.',
    descEn: 'Airport welcome with comfortable transfer.',
    descZh: '',
    priceAr: 'من 80\\\$',
    priceEn: 'From \\\$80',
    priceZh: '',
  },
  {
    id: 'vip-custom',
    parentSlug: 'vip',
    icon: 'consult',
    sortOrder: 9,
    nameAr: 'برنامج حسب الطلب',
    nameEn: 'Custom itinerary',
    nameZh: '',
    descAr: 'صمّم رحلتك مع فريق OBIC.',
    descEn: 'Design your trip with the OBIC team.',
    descZh: '',
    priceAr: 'عرض مخصص',
    priceEn: 'Custom quote',
    priceZh: '',
  },
  {
    id: 'legal-contract',
    parentSlug: 'legal',
    icon: 'doc',
    sortOrder: 0,
    nameAr: 'مراجعة عقود',
    nameEn: 'Contract review',
    nameZh: '',
    descAr: 'مراجعة عقود التوريد والشراكة.',
    descEn: 'Review supply and partnership contracts.',
    descZh: '',
    priceAr: 'من 199\\\$',
    priceEn: 'From \\\$199',
    priceZh: '',
  },
  {
    id: 'legal-compliance',
    parentSlug: 'legal',
    icon: 'doc',
    sortOrder: 1,
    nameAr: 'امتثال وتنظيم',
    nameEn: 'Compliance',
    nameZh: '',
    descAr: 'متطلبات قانونية للعمل في الصين.',
    descEn: 'Legal requirements for operating in China.',
    descZh: '',
    priceAr: 'من 249\\\$',
    priceEn: 'From \\\$249',
    priceZh: '',
  },
  {
    id: 'legal-consult',
    parentSlug: 'legal',
    icon: 'consult',
    sortOrder: 2,
    nameAr: 'استشارة قانونية',
    nameEn: 'Legal consultation',
    nameZh: '',
    descAr: 'جلسة مع مستشار قانوني.',
    descEn: 'Session with a legal advisor.',
    descZh: '',
    priceAr: 'من 99\\\$',
    priceEn: 'From \\\$99',
    priceZh: '',
  },
  {
    id: 'legal-draft',
    parentSlug: 'legal',
    icon: 'doc',
    sortOrder: 3,
    nameAr: 'صياغة مستندات',
    nameEn: 'Document drafting',
    nameZh: '',
    descAr: 'مسودات عقود وخطابات رسمية.',
    descEn: 'Draft contracts and official letters.',
    descZh: '',
    priceAr: 'من 149\\\$',
    priceEn: 'From \\\$149',
    priceZh: '',
  },
  {
    id: 'company-wfoe',
    parentSlug: 'company',
    icon: 'book',
    sortOrder: 4,
    nameAr: 'تسجيل WFOE',
    nameEn: 'WFOE registration',
    nameZh: '',
    descAr: 'شركة ذات مسؤولية محدودة أجنبية.',
    descEn: 'Wholly foreign-owned enterprise setup.',
    descZh: '',
    priceAr: 'من 499\\\$',
    priceEn: 'From \\\$499',
    priceZh: '',
  },
  {
    id: 'company-rep',
    parentSlug: 'company',
    icon: 'book',
    sortOrder: 5,
    nameAr: 'مكتب تمثيل',
    nameEn: 'Representative office',
    nameZh: '',
    descAr: 'تأسيس مكتب تمثيل في الصين.',
    descEn: 'Set up a representative office in China.',
    descZh: '',
    priceAr: 'من 399\\\$',
    priceEn: 'From \\\$399',
    priceZh: '',
  },
  {
    id: 'company-renew',
    parentSlug: 'company',
    icon: 'doc',
    sortOrder: 6,
    nameAr: 'تجديد تراخيص',
    nameEn: 'License renewal',
    nameZh: '',
    descAr: 'متابعة تجديد السجل والتراخيص.',
    descEn: 'Follow up business license renewals.',
    descZh: '',
    priceAr: 'من 199\\\$',
    priceEn: 'From \\\$199',
    priceZh: '',
  },
  {
    id: 'company-change',
    parentSlug: 'company',
    icon: 'doc',
    sortOrder: 7,
    nameAr: 'تعديلات الشركة',
    nameEn: 'Company changes',
    nameZh: '',
    descAr: 'تغيير نشاط أو شركاء أو عنوان.',
    descEn: 'Change activity, partners, or address.',
    descZh: '',
    priceAr: 'عرض حسب الحالة',
    priceEn: 'Quote by case',
    priceZh: '',
  },
  {
    id: 'scholar-abroad',
    parentSlug: 'scholarship',
    icon: 'school',
    sortOrder: 8,
    nameAr: 'الدراسة في الخارج',
    nameEn: 'Study abroad',
    nameZh: '',
    descAr: 'دعم التقديم للجامعات والمنح.',
    descEn: 'University and scholarship applications.',
    descZh: '',
    priceAr: 'استشارة مجانية',
    priceEn: 'Free consult',
    priceZh: '',
  },
  {
    id: 'scholar-chinese',
    parentSlug: 'scholarship',
    icon: 'school',
    sortOrder: 9,
    nameAr: 'تعليم اللغة الصينية',
    nameEn: 'Chinese language',
    nameZh: '',
    descAr: 'برامج لغة فردية أو جماعية.',
    descEn: 'Individual or group language programs.',
    descZh: '',
    priceAr: 'من 80\\\$',
    priceEn: 'From \\\$80',
    priceZh: '',
  },
  {
    id: 'scholar-individual',
    parentSlug: 'scholarship',
    icon: 'consult',
    sortOrder: 0,
    nameAr: 'تعليم فردي',
    nameEn: 'Individual tutoring',
    nameZh: '',
    descAr: 'دروس one-to-one مع مدرب.',
    descEn: 'One-to-one sessions with a tutor.',
    descZh: '',
    priceAr: 'من 25\\\$/ساعة',
    priceEn: 'From \\\$25/hr',
    priceZh: '',
  },
  {
    id: 'scholar-group',
    parentSlug: 'scholarship',
    icon: 'group',
    sortOrder: 1,
    nameAr: 'تعليم جماعي',
    nameEn: 'Group classes',
    nameZh: '',
    descAr: 'فصول جماعية للغة أو التحضير.',
    descEn: 'Group classes for language or prep.',
    descZh: '',
    priceAr: 'من 15\\\$/ساعة',
    priceEn: 'From \\\$15/hr',
    priceZh: '',
  },
  {
    id: 'transfer-assist',
    parentSlug: 'transfer',
    icon: 'consult',
    sortOrder: 2,
    nameAr: 'مساعدة تحويل',
    nameEn: 'Transfer assistance',
    nameZh: '',
    descAr: 'إرشاد آمن للتحويلات التجارية.',
    descEn: 'Guidance for business transfers.',
    descZh: '',
    priceAr: 'طلب فقط',
    priceEn: 'Request only',
    priceZh: '',
  },
  {
    id: 'transfer-quote',
    parentSlug: 'transfer',
    icon: 'book',
    sortOrder: 3,
    nameAr: 'طلب عرض سعر',
    nameEn: 'Request quote',
    nameZh: '',
    descAr: 'احصل على معلومات الرسوم والمسار.',
    descEn: 'Get fee and route information.',
    descZh: '',
    priceAr: 'مجاني',
    priceEn: 'Free',
    priceZh: '',
  },
  {
    id: 'transfer-guide',
    parentSlug: 'transfer',
    icon: 'doc',
    sortOrder: 4,
    nameAr: 'دليل التحويل',
    nameEn: 'Transfer guide',
    nameZh: '',
    descAr: 'خطوات ومتطلبات التحويل.',
    descEn: 'Steps and requirements for transfers.',
    descZh: '',
    priceAr: 'مجاني',
    priceEn: 'Free',
    priceZh: '',
  },
  {
    id: 'ads-brand',
    parentSlug: 'ads',
    icon: 'shop',
    sortOrder: 5,
    nameAr: 'إعلان العلامة',
    nameEn: 'Brand advertising',
    nameZh: '',
    descAr: 'حملات العلامة في السوق الصيني.',
    descEn: 'Brand campaigns in the China market.',
    descZh: '',
    priceAr: 'من 150\\\$',
    priceEn: 'From \\\$150',
    priceZh: '',
  },
  {
    id: 'ads-social',
    parentSlug: 'ads',
    icon: 'shop',
    sortOrder: 6,
    nameAr: 'وسائل التواصل',
    nameEn: 'Social media ads',
    nameZh: '',
    descAr: 'WeChat / Douyin / إعلانات رقمية.',
    descEn: 'WeChat / Douyin / digital ads.',
    descZh: '',
    priceAr: 'من 200\\\$',
    priceEn: 'From \\\$200',
    priceZh: '',
  },
  {
    id: 'ads-campaign',
    parentSlug: 'ads',
    icon: 'book',
    sortOrder: 7,
    nameAr: 'إعداد حملة',
    nameEn: 'Campaign setup',
    nameZh: '',
    descAr: 'تخطيط وتنفيذ حملة إعلانية.',
    descEn: 'Plan and launch an ad campaign.',
    descZh: '',
    priceAr: 'عرض مخصص',
    priceEn: 'Custom quote',
    priceZh: '',
  },
  {
    id: 'biz-sourcing',
    parentSlug: 'biz',
    icon: 'shop',
    sortOrder: 8,
    nameAr: 'توريد منتجات',
    nameEn: 'Product sourcing',
    nameZh: '',
    descAr: 'البحث عن موردين ومنتجات.',
    descEn: 'Find suppliers and products.',
    descZh: '',
    priceAr: 'من 99\\\$',
    priceEn: 'From \\\$99',
    priceZh: '',
  },
  {
    id: 'biz-meetings',
    parentSlug: 'biz',
    icon: 'group',
    sortOrder: 9,
    nameAr: 'تنسيق اجتماعات',
    nameEn: 'Meeting coordination',
    nameZh: '',
    descAr: 'ترتيب meetings مع المصانع.',
    descEn: 'Arrange meetings with factories.',
    descZh: '',
    priceAr: 'من 79\\\$',
    priceEn: 'From \\\$79',
    priceZh: '',
  },
  {
    id: 'biz-ops',
    parentSlug: 'biz',
    icon: 'consult',
    sortOrder: 0,
    nameAr: 'دعم تشغيلي',
    nameEn: 'Operations support',
    nameZh: '',
    descAr: 'متابعة يومية للعمليات في الصين.',
    descEn: 'Day-to-day ops follow-up in China.',
    descZh: '',
    priceAr: 'من 120\\\$',
    priceEn: 'From \\\$120',
    priceZh: '',
  },
  {
    id: 'hr-hire',
    parentSlug: 'hr',
    icon: 'group',
    sortOrder: 1,
    nameAr: 'توظيف',
    nameEn: 'Hiring',
    nameZh: '',
    descAr: 'البحث عن موظفين محليين.',
    descEn: 'Recruit local staff.',
    descZh: '',
    priceAr: 'من 180\\\$',
    priceEn: 'From \\\$180',
    priceZh: '',
  },
  {
    id: 'hr-payroll',
    parentSlug: 'hr',
    icon: 'doc',
    sortOrder: 2,
    nameAr: 'رواتب وامتثال',
    nameEn: 'Payroll & compliance',
    nameZh: '',
    descAr: 'إرشاد رواتب وقوانين العمل.',
    descEn: 'Payroll and labor law guidance.',
    descZh: '',
    priceAr: 'من 150\\\$',
    priceEn: 'From \\\$150',
    priceZh: '',
  },
  {
    id: 'hr-contracts',
    parentSlug: 'hr',
    icon: 'doc',
    sortOrder: 3,
    nameAr: 'عقود موظفين',
    nameEn: 'Staff contracts',
    nameZh: '',
    descAr: 'صياغة عقود عمل محلية.',
    descEn: 'Draft local employment contracts.',
    descZh: '',
    priceAr: 'من 99\\\$',
    priceEn: 'From \\\$99',
    priceZh: '',
  },
  {
    id: 'ins-health',
    parentSlug: 'insurance',
    icon: 'health',
    sortOrder: 4,
    nameAr: 'تأمين صحي',
    nameEn: 'Health insurance',
    nameZh: '',
    descAr: 'خطط صحية للمقيمين والزوار.',
    descEn: 'Health plans for residents and visitors.',
    descZh: '',
    priceAr: 'من 50\\\$',
    priceEn: 'From \\\$50',
    priceZh: '',
  },
  {
    id: 'ins-travel',
    parentSlug: 'insurance',
    icon: 'health',
    sortOrder: 5,
    nameAr: 'تأمين سفر',
    nameEn: 'Travel insurance',
    nameZh: '',
    descAr: 'تغطية أثناء الرحلات التجارية.',
    descEn: 'Coverage during business trips.',
    descZh: '',
    priceAr: 'من 35\\\$',
    priceEn: 'From \\\$35',
    priceZh: '',
  },
  {
    id: 'ins-claims',
    parentSlug: 'insurance',
    icon: 'consult',
    sortOrder: 6,
    nameAr: 'متابعة مطالبات',
    nameEn: 'Claims support',
    nameZh: '',
    descAr: 'مساعدة في تقديم المطالبات.',
    descEn: 'Help filing insurance claims.',
    descZh: '',
    priceAr: 'من 49\\\$',
    priceEn: 'From \\\$49',
    priceZh: '',
  },
  {
    id: 'expand-market',
    parentSlug: 'expand',
    icon: 'consult',
    sortOrder: 7,
    nameAr: 'دخول السوق',
    nameEn: 'Market entry',
    nameZh: '',
    descAr: 'استراتيجية دخول السوق الصيني.',
    descEn: 'China market entry strategy.',
    descZh: '',
    priceAr: 'مخصص',
    priceEn: 'Custom',
    priceZh: '',
  },
  {
    id: 'expand-gtm',
    parentSlug: 'expand',
    icon: 'book',
    sortOrder: 8,
    nameAr: 'Go-to-market',
    nameEn: 'Go-to-market',
    nameZh: '',
    descAr: 'خطة إطلاق منتج أو خدمة.',
    descEn: 'Product or service launch plan.',
    descZh: '',
    priceAr: 'مخصص',
    priceEn: 'Custom',
    priceZh: '',
  },
  {
    id: 'expand-partner',
    parentSlug: 'expand',
    icon: 'group',
    sortOrder: 9,
    nameAr: 'بحث شركاء',
    nameEn: 'Partner search',
    nameZh: '',
    descAr: 'العثور على موزعين أو شركاء.',
    descEn: 'Find distributors or partners.',
    descZh: '',
    priceAr: 'مخصص',
    priceEn: 'Custom',
    priceZh: '',
  },
  {
    id: 'tech-it',
    parentSlug: 'tech',
    icon: 'consult',
    sortOrder: 0,
    nameAr: 'دعم IT',
    nameEn: 'IT support',
    nameZh: '',
    descAr: 'حل مشاكل أنظمة وتطبيقات.',
    descEn: 'Resolve systems and app issues.',
    descZh: '',
    priceAr: 'من 80\\\$',
    priceEn: 'From \\\$80',
    priceZh: '',
  },
  {
    id: 'tech-setup',
    parentSlug: 'tech',
    icon: 'book',
    sortOrder: 1,
    nameAr: 'إعداد أنظمة',
    nameEn: 'System setup',
    nameZh: '',
    descAr: 'تهيئة أدوات العمل للفريق.',
    descEn: 'Set up team work tools.',
    descZh: '',
    priceAr: 'من 120\\\$',
    priceEn: 'From \\\$120',
    priceZh: '',
  },
  {
    id: 'plan-workshop',
    parentSlug: 'plan',
    icon: 'group',
    sortOrder: 2,
    nameAr: 'ورشة تخطيط',
    nameEn: 'Planning workshop',
    nameZh: '',
    descAr: 'جلسة تخطيط أعمال عملية.',
    descEn: 'Hands-on business planning session.',
    descZh: '',
    priceAr: 'من 220\\\$',
    priceEn: 'From \\\$220',
    priceZh: '',
  },
  {
    id: 'plan-feasibility',
    parentSlug: 'plan',
    icon: 'doc',
    sortOrder: 3,
    nameAr: 'دراسة جدوى',
    nameEn: 'Feasibility study',
    nameZh: '',
    descAr: 'تحليل جدوى مشروع في الصين.',
    descEn: 'Feasibility analysis for China projects.',
    descZh: '',
    priceAr: 'مخصص',
    priceEn: 'Custom',
    priceZh: '',
  },
  {
    id: 'cars-rent',
    parentSlug: 'cars',
    icon: 'car',
    sortOrder: 4,
    nameAr: 'تأجير سيارة',
    nameEn: 'Car rental',
    nameZh: '',
    descAr: 'تأجير يومي أو أسبوعي.',
    descEn: 'Daily or weekly car rental.',
    descZh: '',
    priceAr: 'من 35\\\$',
    priceEn: 'From \\\$35',
    priceZh: '',
  },
  {
    id: 'cars-airport',
    parentSlug: 'cars',
    icon: 'car',
    sortOrder: 5,
    nameAr: 'نقل مطار',
    nameEn: 'Airport transfer',
    nameZh: '',
    descAr: 'استقبال من/إلى المطار.',
    descEn: 'Airport pickup or drop-off.',
    descZh: '',
    priceAr: 'من 40\\\$',
    priceEn: 'From \\\$40',
    priceZh: '',
  },
  {
    id: 'cars-driver',
    parentSlug: 'cars',
    icon: 'consult',
    sortOrder: 6,
    nameAr: 'سائق خاص',
    nameEn: 'Private driver',
    nameZh: '',
    descAr: 'سائق مع مركبة ليوم كامل.',
    descEn: 'Driver with car for a full day.',
    descZh: '',
    priceAr: 'من 80\\\$',
    priceEn: 'From \\\$80',
    priceZh: '',
  },
  {
    id: 'property-rent',
    parentSlug: 'property',
    icon: 'home',
    sortOrder: 7,
    nameAr: 'إيجار',
    nameEn: 'Rent',
    nameZh: '',
    descAr: 'شقق ومكاتب للإيجار.',
    descEn: 'Apartments and offices for rent.',
    descZh: '',
    priceAr: 'استشارة مجانية',
    priceEn: 'Consult free',
    priceZh: '',
  },
  {
    id: 'property-buy',
    parentSlug: 'property',
    icon: 'home',
    sortOrder: 8,
    nameAr: 'شراء',
    nameEn: 'Buy',
    nameZh: '',
    descAr: 'مساعدة في شراء عقار.',
    descEn: 'Assistance buying property.',
    descZh: '',
    priceAr: 'عرض مخصص',
    priceEn: 'Custom quote',
    priceZh: '',
  },
  {
    id: 'property-office',
    parentSlug: 'property',
    icon: 'shop',
    sortOrder: 9,
    nameAr: 'مكاتب أعمال',
    nameEn: 'Business offices',
    nameZh: '',
    descAr: 'مكاتب جاهزة في ييو وقوانغتشو.',
    descEn: 'Ready offices in Yiwu & Guangzhou.',
    descZh: '',
    priceAr: 'عرض حسب المساحة',
    priceEn: 'Quote by size',
    priceZh: '',
  },
  {
    id: 'delivery-domestic',
    parentSlug: 'delivery',
    icon: 'shop',
    sortOrder: 0,
    nameAr: 'شحن داخلي',
    nameEn: 'Domestic shipping',
    nameZh: '',
    descAr: 'توصيل داخل الصين.',
    descEn: 'Delivery within China.',
    descZh: '',
    priceAr: 'عرض حسب الوزن',
    priceEn: 'Quote by weight',
    priceZh: '',
  },
  {
    id: 'delivery-intl',
    parentSlug: 'delivery',
    icon: 'shop',
    sortOrder: 1,
    nameAr: 'شحن دولي',
    nameEn: 'International shipping',
    nameZh: '',
    descAr: 'شحن من الصين للخارج.',
    descEn: 'Shipping from China abroad.',
    descZh: '',
    priceAr: 'عرض مخصص',
    priceEn: 'Custom quote',
    priceZh: '',
  },
  {
    id: 'delivery-express',
    parentSlug: 'delivery',
    icon: 'speed',
    sortOrder: 2,
    nameAr: 'توصيل سريع',
    nameEn: 'Express delivery',
    nameZh: '',
    descAr: 'خدمة توصيل عاجلة.',
    descEn: 'Urgent express delivery.',
    descZh: '',
    priceAr: 'من 25\\\$',
    priceEn: 'From \\\$25',
    priceZh: '',
  },
  {
    id: 'consult-biz',
    parentSlug: 'consultations',
    icon: 'consult',
    sortOrder: 3,
    nameAr: 'استشارة أعمال',
    nameEn: 'Business consultation',
    nameZh: '',
    descAr: 'جلسة مع مستشار أعمال.',
    descEn: 'Session with a business advisor.',
    descZh: '',
    priceAr: 'من 79\\\$',
    priceEn: 'From \\\$79',
    priceZh: '',
  },
  {
    id: 'consult-market',
    parentSlug: 'consultations',
    icon: 'consult',
    sortOrder: 4,
    nameAr: 'دراسة سوق',
    nameEn: 'Market study',
    nameZh: '',
    descAr: 'تحليل سوق ومنتجات.',
    descEn: 'Market and product analysis.',
    descZh: '',
    priceAr: 'عرض مخصص',
    priceEn: 'Custom quote',
    priceZh: '',
  },
  {
    id: 'consult-tax',
    parentSlug: 'consultations',
    icon: 'doc',
    sortOrder: 5,
    nameAr: 'استشارة ضريبية',
    nameEn: 'Tax consultation',
    nameZh: '',
    descAr: 'إرشاد ضريبي للشركات.',
    descEn: 'Tax guidance for companies.',
    descZh: '',
    priceAr: 'من 99\\\$',
    priceEn: 'From \\\$99',
    priceZh: '',
  },
  {
    id: 'trans-doc',
    parentSlug: 'translation',
    icon: 'doc',
    sortOrder: 6,
    nameAr: 'ترجمة مستندات',
    nameEn: 'Document translation',
    nameZh: '',
    descAr: 'عقود وشهادات ووثائق رسمية.',
    descEn: 'Contracts, certificates, official docs.',
    descZh: '',
    priceAr: 'من 25\\\$',
    priceEn: 'From \\\$25',
    priceZh: '',
  },
  {
    id: 'trans-interpret',
    parentSlug: 'translation',
    icon: 'consult',
    sortOrder: 7,
    nameAr: 'ترجمة فورية',
    nameEn: 'On-site interpreting',
    nameZh: '',
    descAr: 'مرافق مترجم في الاجتماعات.',
    descEn: 'Interpreter for meetings & visits.',
    descZh: '',
    priceAr: 'من 50\\\$',
    priceEn: 'From \\\$50',
    priceZh: '',
  },
  {
    id: 'trans-certified',
    parentSlug: 'translation',
    icon: 'doc',
    sortOrder: 8,
    nameAr: 'ترجمة معتمدة',
    nameEn: 'Certified translation',
    nameZh: '',
    descAr: 'ترجمة معتمدة للجهات الرسمية.',
    descEn: 'Certified translation for authorities.',
    descZh: '',
    priceAr: 'من 35\\\$',
    priceEn: 'From \\\$35',
    priceZh: '',
  },
  {
    id: 'tour-package',
    parentSlug: 'tourism',
    icon: 'book',
    sortOrder: 9,
    nameAr: 'باقة سياحية',
    nameEn: 'Tour package',
    nameZh: '',
    descAr: 'برنامج جاهز لعدة أيام.',
    descEn: 'Ready multi-day tour package.',
    descZh: '',
    priceAr: 'عرض مخصص',
    priceEn: 'Custom quote',
    priceZh: '',
  },
  {
    id: 'tour-custom',
    parentSlug: 'tourism',
    icon: 'consult',
    sortOrder: 0,
    nameAr: 'برنامج حسب الطلب',
    nameEn: 'Custom itinerary',
    nameZh: '',
    descAr: 'صمّم رحلتك مع فريق OBIC.',
    descEn: 'Design your trip with OBIC.',
    descZh: '',
    priceAr: 'عرض مخصص',
    priceEn: 'Custom quote',
    priceZh: '',
  },
  {
    id: 'tour-guide',
    parentSlug: 'tourism',
    icon: 'group',
    sortOrder: 1,
    nameAr: 'مرشد سياحي',
    nameEn: 'Tour guide',
    nameZh: '',
    descAr: 'مرشد يتحدث العربية/الإنجليزية.',
    descEn: 'Arabic/English speaking guide.',
    descZh: '',
    priceAr: 'من 60\\\$',
    priceEn: 'From \\\$60',
    priceZh: '',
  },
];