// Made by Dr Ali
// Message body + optional image/file metadata (URL from POST /v1/uploads).

import {
  Column,
  CreateDateColumn,
  Entity,
  JoinColumn,
  ManyToOne,
  PrimaryGeneratedColumn,
} from 'typeorm';
import { User } from '../users/user.entity';
import { Conversation } from './conversation.entity';

export enum AttachmentKind {
  None = 'none',
  Image = 'image',
  File = 'file',
  /** Voice note (m4a/aac/mp3…) from hold-to-talk. */
  Audio = 'audio',
  /** Short video clip from camera/gallery. */
  Video = 'video',
}

@Entity({ name: 'messages' })
export class Message {
  @PrimaryGeneratedColumn('uuid')
  id!: string;

  @Column({ name: 'conversation_id', type: 'uuid' })
  conversationId!: string;

  @ManyToOne(() => Conversation, (c) => c.messages, { onDelete: 'CASCADE' })
  @JoinColumn({ name: 'conversation_id' })
  conversation!: Conversation;

  @Column({ name: 'sender_id', type: 'uuid' })
  senderId!: string;

  @ManyToOne(() => User, { onDelete: 'CASCADE' })
  @JoinColumn({ name: 'sender_id' })
  sender!: User;

  @Column({ type: 'text', default: '' })
  body!: string;

  @Column({
    name: 'attachment_kind',
    type: 'enum',
    enum: AttachmentKind,
    default: AttachmentKind.None,
  })
  attachmentKind!: AttachmentKind;

  @Column({ name: 'attachment_name', type: 'varchar', length: 255, nullable: true })
  attachmentName!: string | null;

  @Column({ name: 'attachment_url', type: 'varchar', length: 1024, nullable: true })
  attachmentUrl!: string | null;

  /** Phase 5 — true when body was generated by OBIC AI (auto-reply / bot). */
  @Column({ name: 'is_ai', type: 'boolean', default: false })
  isAi!: boolean;

  @CreateDateColumn({ name: 'created_at', type: 'timestamptz' })
  createdAt!: Date;
}
